=== alexprometeo/lm_dam/2daEva/XML/03_xmlSchema/confBD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="conf">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="base_datos" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="user" type="xs:string"/>
                            <xs:element name="password" type="xs:string"></xs:element>
                            <xs:element name="port" type="xs:integer"></xs:element>
                            <xs:element name="max_connections" type="xs:integer"></xs:element>
                            <!-- <xs:element name="access_mode" type="xs:string"> -->
                            <xs:element name="access_mode">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="local"></xs:enumeration>
                                        <xs:enumeration value="remoto"></xs:enumeration>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="host" type="xs:string" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== alexprometeo/lm_dam/2daEva/XML/03_xmlSchema/confBD.xml
<?xml version="1.0" encoding="UTF-8"?>
<conf xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="confBD.xsd">
    <base_datos host="127.0.0.1">
        <user>pepe</user>
        <password>passs_1234</password>
        <port>3000</port>
        <max_connections>1000</max_connections>
        <access_mode>local</access_mode>
    </base_datos>

    <base_datos host="google.com">
        <user>pepe</user>
        <password>passs_1234</password>
        <port>3000</port>
        <max_connections>1000</max_connections>
        <access_mode>local</access_mode>
    </base_datos>    
</conf>
