=== alexprometeo/lm_dam/2da_Eva/LenguajeMarcas/repasoXML_JSON/assets/configuracion_web.dtd
<!ELEMENT configuracion (sitio_web+)>
<!ELEMENT sitio_web (nombre, dominio, tecnologias, secciones, servidor)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT dominio (#PCDATA)>
<!ELEMENT tecnologias (tecnologia+)>
<!ELEMENT tecnologia (#PCDATA)>
<!ELEMENT secciones (seccion+)>
<!ELEMENT seccion (#PCDATA)>   
<!ELEMENT servidor (puerto, bbdd)> 
<!ELEMENT puerto (#PCDATA)>   
<!ELEMENT bbdd (#PCDATA)>

=== alexprometeo/lm_dam/2da_Eva/LenguajeMarcas/repasoXML_JSON/assets/configuracion_web.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
    Crea un XML con la info de un sitio web:
     - Nombre del sitio
     - Dominio
     - Tecnologias utilizadas (con subelementos tecnologia con valores como HTML, JS, CSS)
     - Secciones del sitio (con subelementos seccion con valores como Inicio, Blog, Contacto)
     - Configuracion servidor (con subelementos puerto y base datos)
-->

<!-- Validar mediante DTD interno -->
<!-- <!DOCTYPE configuracion [
    <!ELEMENT configuracion (sitio_web+)>
    <!ELEMENT sitio_web (nombre, dominio, tecnologias, secciones, servidor)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT dominio (#PCDATA)>
    <!ELEMENT tecnologias (tecnologia+)>
    <!ELEMENT tecnologia (#PCDATA)>
    <!ELEMENT secciones (seccion+)>
    <!ELEMENT seccion (#PCDATA)>   
    <!ELEMENT servidor (puerto, bbdd)> 
    <!ELEMENT puerto (#PCDATA)>   
    <!ELEMENT bbdd (#PCDATA)>
]> -->

<!-- Enlazar a un DTD externo -->
<!DOCTYPE configuracion SYSTEM "configuracion_web.dtd">
<configuracion>
    <sitio_web>
        <nombre>CucuSoft</nombre>
        <dominio>www.cucusoft.ro</dominio>
        <tecnologias>
            <tecnologia>HTML</tecnologia>
            <tecnologia>JS</tecnologia>
            <tecnologia>CSS</tecnologia>
        </tecnologias>
        <secciones>
            <seccion>Inicio</seccion>
            <seccion>Blog</seccion>
            <seccion>Contacto</seccion>
        </secciones>
        <servidor>
            <puerto>3001</puerto>
            <bbdd>SQL Server</bbdd>
        </servidor>
    </sitio_web>
</configuracion>
